imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*,  build/coverage/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
        override:
            - true
            - command: "make install test"
            - command: "make phpunit"
            - command: "make phpcs phpmd phpstan"
            - command: "php artisan migrate"
              coverage:
                  file: "build/coverage.clover"
                  format: "php-clover"
