imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*,  build/*, database/*]

build:
    nodes:
        analysis:
          project_setup:
            override: true
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
          override:
            - php-scrutinizer-run
            - command: 'vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php'
            - command: "make phpunit"
            - command: "make phpcs phpmd phpstan"
              coverage:
                  file: "build/coverage.clover"
                  format: "php-clover"
