var classes = [
    {
        "name": "App\\Controllers\\Books\\BooksTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\DB"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 4,
        "volume": 14,
        "difficulty": 2.5,
        "effort": 35,
        "level": 0.4,
        "bugs": 0,
        "time": 2,
        "intelligentContent": 5.6,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 110.98,
        "mIwoC": 71.02,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "App\\Controllers\\Books\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Dice\\DiceGameTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Dice\\DiceResults"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 2,
        "length": 35,
        "vocabulary": 17,
        "volume": 143.06,
        "difficulty": 3.85,
        "effort": 550.24,
        "level": 0.26,
        "bugs": 0.05,
        "time": 31,
        "intelligentContent": 37.2,
        "number_operators": 10,
        "number_operands": 25,
        "number_operators_unique": 4,
        "number_operands_unique": 13,
        "cloc": 11,
        "loc": 32,
        "lloc": 21,
        "mi": 95.22,
        "mIwoC": 55.8,
        "commentWeight": 39.42,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "package": "App\\Controllers\\Dice\\",
        "pageRank": 0.31,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Dice\\GameForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Illuminate\\Http\\Request",
            "App\\Controllers\\Dice\\DiceGameTable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 89,
        "vocabulary": 21,
        "volume": 390.92,
        "difficulty": 6.42,
        "effort": 2508.38,
        "level": 0.16,
        "bugs": 0.13,
        "time": 139,
        "intelligentContent": 60.92,
        "number_operators": 12,
        "number_operands": 77,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 0,
        "loc": 38,
        "lloc": 38,
        "mi": 46.85,
        "mIwoC": 46.85,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 256.24,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 0.24,
        "totalSystemComplexity": 256.24,
        "package": "App\\Controllers\\Dice\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Dice\\PlayForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Illuminate\\Http\\Request"
        ],
        "parents": [],
        "lcom": 1,
        "length": 75,
        "vocabulary": 24,
        "volume": 343.87,
        "difficulty": 6.3,
        "effort": 2166.39,
        "level": 0.16,
        "bugs": 0.11,
        "time": 120,
        "intelligentContent": 54.58,
        "number_operators": 12,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 0,
        "loc": 33,
        "lloc": 33,
        "mi": 48.58,
        "mIwoC": 48.58,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 169.29,
        "totalStructuralComplexity": 169,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 169.29,
        "package": "App\\Controllers\\Dice\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Dice\\StartForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Http\\Request",
            "App\\Models\\Dice\\Game"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 10,
        "volume": 112.95,
        "difficulty": 3.5,
        "effort": 395.31,
        "level": 0.29,
        "bugs": 0.04,
        "time": 22,
        "intelligentContent": 32.27,
        "number_operators": 6,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.11,
        "mIwoC": 58.11,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 49.25,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 49.25,
        "package": "App\\Controllers\\Dice\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Guess\\FailForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Http\\Request"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 9,
        "volume": 47.55,
        "difficulty": 3,
        "effort": 142.65,
        "level": 0.33,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 62.99,
        "mIwoC": 62.99,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Controllers\\Guess\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Guess\\GuessForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "Illuminate\\Http\\Request",
            "App\\Models\\Guess\\Guess",
            "Illuminate\\Http\\Request"
        ],
        "parents": [],
        "lcom": 2,
        "length": 113,
        "vocabulary": 31,
        "volume": 559.82,
        "difficulty": 15.3,
        "effort": 8567.74,
        "level": 0.07,
        "bugs": 0.19,
        "time": 476,
        "intelligentContent": 36.58,
        "number_operators": 25,
        "number_operands": 88,
        "number_operators_unique": 8,
        "number_operands_unique": 23,
        "cloc": 0,
        "loc": 54,
        "lloc": 54,
        "mi": 41.89,
        "mIwoC": 41.89,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 64.78,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 1.56,
        "totalSystemComplexity": 129.56,
        "package": "App\\Controllers\\Guess\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Guess\\WinForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Http\\Request"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 9,
        "volume": 47.55,
        "difficulty": 3,
        "effort": 142.65,
        "level": 0.33,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 62.99,
        "mIwoC": 62.99,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Controllers\\Guess\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]